config:
  #This determines the folder capes are stored in
  #Note capes should be png files
  #If left as default, will disable capes
  #Default: /path/to/cape/directory/
  internalCapePath: /path/to/cape/directory/
  #The external folder where capes are stored
  #This address must be reachable by the client for capes to work!
  externalCapePath: http://yourwebsite.com/capefolder/
classes:
  alchemist:
    #The catalysts to be used in alchemist recipes
    #Options can be any vanilla item or "catalyst" for the custom item 
    upgradeCatalyst: slimeball
    downgradeCatalyst: feather
    #The uses a catalyst item has before disintegrating
    #If this is negative the item has infinite uses
    #This only affects the custom item
    catalystUses: -1
    #Determines whether or not to return the catalysts on use
    #These have no effect on the custom item
    returnUpgradeCatalyst: false
    returnDowngradeCatalyst: false
#This contains a single example user
users:
  example_user: 
    PrimaryClass: Warrior
    SecondaryClass: Enchanter
    #This assumes that a cape file with this name and filetype png exists at capePath
    #Default location for this cape would therefore be:
    #/path/to/cape/directory/Admin.png
    CurrentCape: Admin