config:
  #The external folder where custom textures are stored
  #Note textures should be png files
  #This address must be reachable by the client for custom items to work!
  externalResourcePath: https://dl.dropboxusercontent.com/u/16478138/Toybox/
  #The list of capes
  #Capes listed here must be found at the external resource path as PNG files
  #If class capes are removed, that class will not have a cape
  #Access to capes is denoted by the permission node toybox.capes.capename
  #Granting players access to a class cape permission node is not recommended.
  capeList:
    - Alchemist
    - Archer
    - Cook
    - Enchanter
    - Farmer
    - Lumberjack
    - Oreworker
    - Outsider
    - Warrior
classes:
  alchemist:
    #The catalysts to be used in alchemist recipes
    #Options can be any vanilla item or "catalyst" for the custom item 
    upgradeCatalyst: slimeball
    downgradeCatalyst: feather
    #The uses a catalyst item has before disintegrating
    #If this is negative the item has infinite uses
    #This only affects the custom item
    catalystUses: -1
    #Determines whether or not to return the catalysts on use
    #These have no effect on the custom item
    returnUpgradeCatalyst: false
    returnDowngradeCatalyst: false
#This contains a single example user
users:
  example_user: 
    PrimaryClass: Warrior
    SecondaryClass: Enchanter
    #This assumes that a cape file with this name and filetype png exists at capePath
    #Default location for this cape would therefore be:
    #/path/to/cape/directory/Admin.png
    CurrentCape: Admin