config: 
  #Enable this to show all debug messages.
  #This will produce a lot of output!
  #Default: false
  debug: false
  #This determines the folder capes are stored in
  #Note capes should be png files
  #If left as default, will disable capes
  #Default: /path/to/cape/directory/
  capePath: /path/to/cape/directory/
#This contains a single example user
users:
  example_user: 
    PrimaryClass: Warrior
    SecondaryClass: Enchanter
    #This assumes that a cape file with this name and filetype png exists at capePath
    #Default location for this cape would therefore be:
    #/path/to/cape/directory/Admin.png
    CurrentCape: Admin
    #This list shows most capes the player is allowed.
    #The player is also allowed any capes with names matching the player classes
    #So the capes example_user is allowed are Admin.png, Developer.png, Warrior.png and Enchanter.png
    #If the user is wearing a class cape and removes that class, the cape will be automatically removed.
    AllowedCapes:
      - Admin
      - Developer